services:
  ingress-ome:
    image: airensoft/ovenmediaengine:dev
    ports:
      # Expose RTMP Ingress port to host machine
      - 1935:1935
      # Expose Rest API port for host machine for debugging
      - 8081:8081
      # WebRTC Streaming ports 3332 for signaling and 10000-10005 for ICE and 3478 for TCP relay (TURN) for ingress stream monitoring
      - 3332:3333
      - 10000-10005:10000-10005/udp
      - 3478:3478
    volumes:
      - ./ingress_ome/conf:/opt/ovenmediaengine/bin/origin_conf
  origin-ome:
    image: airensoft/ovenmediaengine:dev
    ports:
      # Expose Rest API port for host machine for debugging
      - 8082:8081
      # (LL)HLS Streaming port
      - 3333:3333
    volumes:
      - ./origin_ome/conf:/opt/ovenmediaengine/bin/origin_conf
  control-server:
    restart: always
    build: 
      dockerfile: ControlServer.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./control_server:/app