services:
  ingress-ome:
    image: airensoft/ovenmediaengine:dev
    ports:
      # RTMP Ingress port
      - 1935:1935
      # Expose Rest API port for host machine for debugging
      - 8081:8081
      # WebRTC Streaming ports 3332 for signaling and 10000-10005 for ICE and 3477 for TCP relay (TURN)
      - 3332:3333
      - 10000-10005:10000-10005/udp
      - 3477:3477
    volumes:
      - ./ingress_ome/conf:/opt/ovenmediaengine/bin/origin_conf
  origin-ome:
    image: airensoft/ovenmediaengine:dev
    ports:
      # Expose RTMP Ingress port for host machine for debugging
      - 1936:1935
      # Expose Rest API port for host machine for debugging
      - 8082:8081
      # (LL)HLS Streaming port
      - 3333:3333
    volumes:
      - ./origin_ome/conf:/opt/ovenmediaengine/bin/origin_conf
  control-server:
    build: 
      dockerfile: ControlServer.Dockerfile
    ports:
      - 5000:5000